name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Ou qualquer outra branch que você esteja usando

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Aqui publicamos tudo da raiz do repositório

